# Generated by Django 3.0.5 on 2020-05-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200505_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slides',
        ),
        migrations.AlterField(
            model_name='slide',
            name='fk',
            field=models.IntegerField(null=True),
        ),
    ]
