# Generated by Django 3.0.5 on 2020-05-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200506_1506'),
        ('quiz', '0011_auto_20200506_1713'),
    ]

    operations = [
    ]
