# Generated by Django 3.0.5 on 2020-05-07 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_merge_20200506_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionslide',
            options={'ordering': ['slide_number']},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['round_number']},
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterOrderWithRespectTo(
            name='questionslide',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='round',
            order_with_respect_to=None,
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Round')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category'),
        ),
    ]
