# Generated by Django 3.0.5 on 2020-05-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20200508_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='degradation',
            field=models.FloatField(default=0),
        ),
    ]
