# Generated by Django 3.0.5 on 2020-05-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_round_degradation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='degradation',
        ),
    ]
